version: "3.7"
services:
  bookify:
    image: bookify-api
    container_name: bookify-api
    build:
      context: .
      args:
        - PORT = ${PORT}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - bookify-nw
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  bookify-nw:
    driver: bridge

volumes:
  postgres-data:
    driver: local
