version: "3.7"
services:
  bookify:
    image: bookify-api
    container_name: bookify-api
    build:
      context: .
      args:
        - PORT = ${PORT}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - bookify-nw
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules

  mongo:
    image: mongo:7.0
    container_name: bookify-db
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    networks:
      - bookify-nw
    volumes:
      - mongo-data:/data/db

networks:
  bookify-nw:
    driver: bridge

volumes:
  mongo-data:
    driver: local
